theme: jekyll-theme-cayman
title: Natural disasters through quotes
description: ADA Project 2021 <br> Raphael Marietan, Amine Ahmed Ghariani, Luca Bracone, Omid Karimi
github:
  repository_url: https://github.com/epfl-ada/ada-2021-project-marietan-ghariani-bracone-karimi
